trigger:
- main

pool:
  name: 'Default'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: 'Build and Pack'
  inputs:
    command: 'pack'
    packagesToPack: '$(Build.ArtifactStagingDirectory)Ascetic.Integration.Slack/Ascetic.Integration.Slack.csproj'
    versioningScheme: 'byEnvVar'
    versionEnvVar: 'Version'
- task: NuGetCommand@2
  displayName: 'Push to NuGet'
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'ascetic.integration.slack'